spring:
  application:
    name: spring-graphql
  graphql:
    graphiql:
      enabled: true
#    cors:
#      allowed-origins: *
  datasource:
    name: people
    generate-unique-name: false
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
